[licenses]
# only check licenses for crates in your dependency graph
pull-prefix = []
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "0BSD",
    "CC0-1.0",
    "Unlicense",
]
# if you need to explicitly allow dual-licensed crates
allow-expressions = [
    "MIT OR Apache-2.0",
    "Apache-2.0 OR MIT",
    "0BSD OR MIT OR Apache-2.0",
    "Unlicense OR MIT",
    "CC0-1.0 OR Apache-2.0 OR Apache-2.0 WITH LLVM-exception",
]

[deny]
licenses = true
duplicates = true
