[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "0BSD",
    "Unlicense",
    # Dual-/multi-license expressions are perfectly valid here:
    "MIT OR Apache-2.0",
    "Apache-2.0 OR MIT",
    "0BSD OR MIT OR Apache-2.0",
    "Unlicense OR MIT",
    "CC0-1.0 OR Apache-2.0 OR Apache-2.0 WITH LLVM-exception",
]

[sources]
allow-registry = ["crates-io"]
