# deny.toml

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "0BSD",
    "Unlicense",
    "Unicode-3.0",
    "Zlib",
]

[sources]
allow-registry = [
    "https://github.com/rust-lang/crates.io-index"
]